name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install packages
        if: startsWith(matrix.os, 'ubuntu')
        run: |
            sudo apt-get update
            sudo apt-get install -y libegl1  # Needed for pyqt6

      - name: Update PATH macos
        if: startsWith(matrix.os, 'macos')
        run: echo "/Users/runner/.local/bin" >> $GITHUB_PATH

      - name: Update PATH windows
        if: startsWith(matrix.os, 'windows')
        run: >
            echo "C:\Users\runneradmin\AppData\Roaming\Python\Scripts"
                 | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install poetry dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

#      - name: Run unit tests
#        uses: coactions/setup-xvfb@v1
#        with:
#          run: |
#            poetry run python -m pytest

      - name: Run unit tests
        run: |
            poetry run python -m pytest
